cache:
  paths:
    - node_modules/

部署到预发:
  script:
    - npm install --registry=http://npm.hekr.me
    - npm run build:test
    - sh deploy.sh hekr-hangye/xiaofang-test/web
  tags:
    - test
  only:
    - dev
  when: manual
  environment:
    name: env-test
    url: https://hy.hekr.me/xiaofang-test/web/index.html

部署到线上:
  script:
    - npm install --registry=http://npm.hekr.me
    - npm run build:prod
    - sh deploy.sh hekr-hangye/xiaofang/web
  tags:
    - test
  only:
    - master
  when: manual
  environment:
    name: env-prod
    url: https://hy.hekr.me/xiaofang/web/index.html
